### ISSUE TITLE
Erro ao executar initdb

### ISSUE THREAD

**Issue by alexandre** [okfn-brasil/cuidando2#67]
Eu estou trabalhando no script de setup e apareceu algo parecido com o primeiro erro:

``` shell
alexandre@lastzion ~/Development/okbr-cuidando2/cuidando-setup/viralata (master) $ python manage.py initdb
Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    from viralata.app import app
  File "/home/alexandre/Development/okbr-cuidando2/cuidando-setup/viralata/viralata/app.py", line 8, in <module>
    from extensions import db, sv
  File "/home/alexandre/Development/okbr-cuidando2/cuidando-setup/viralata/viralata/extensions.py", line 6, in <module>
    from viratoken import SignerVerifier
ImportError: No module named viratoken
```

O script está praticamente pronto, mas parece que temos algum problema com o pacote. Usar `python setup.py develop` como indicado não funciona, eu precisei instalar pelo modo convencional `python setup.py install`

**Comment by andresmrm** [comment]
Dei uma olhada no script e para mim parece ótimo! Mas não testei. Não sei
bem porque está dando esse erro. Será que não está usando o mesmo virtualenv
para tudo?

[2015-08-20 06:53] Alexandre:

**Comment by alexandre** [comment]
Eu estou usando o mesmo venv...
Ontem eu fiz mais algum testes e já sei como deixar 100%. O que falta:
- Depois do python setup.py develop, chamar a opção install
- A execução do setup.py deve ser feita dentro do diretório/modulo
  relacionado. Eu fiz algo como viralata/setup.py install e o diretorio egg
  ficou fora do módulo.
- Gerar uma chave com o ssh-keygen, copiar a chave para o
  <modulo>/settings/ e copiar a chave publica para <modulo>/settings/keypub
  (renomear de .pub para keypub)

Eu fecho essa issue quando finalizar essa questão.

[ ]'s

2015-08-21 8:52 GMT-03:00 Andrés Martano notifications@github.com:

> Dei uma olhada no script e para mim parece ótimo! Mas não testei. Não sei
> bem porque está dando esse erro. Será que não está usando o mesmo
> virtualenv
> para tudo?
> 
> [2015-08-20 06:53] Alexandre:
> 
> > Eu estou trabalhando no script de setup e apareceu algo parecido com o
> > primeiro
> > erro:
> > 
> > alexandre@lastzion ~/Development/okbr-cuidando2/cuidando-setup/viralata
> > (master) $ python manage.py initdb
> > Traceback (most recent call last):
> > File "manage.py", line 6, in <module>
> > from viralata.app import app
> > File
> > "/home/alexandre/Development/okbr-cuidando2/cuidando-setup/viralata/viralata/app.py",
> > line 8, in <module>
> > from extensions import db, sv
> > File
> > "/home/alexandre/Development/okbr-cuidando2/cuidando-setup/viralata/viralata/extensions.py",
> > line 6, in <module>
> > from viratoken import SignerVerifier
> > ImportError: No module named viratoken
> > 
> > O script está praticamente pronto, mas parece que temos algum problema
> > com o
> > pacote. Usar python setup.py develop como indicado não funciona, eu
> > precisei
> > instalar pelo modo convencional python setup.py install
> > 
> > —
> > Reply to this email directly or view it on GitHub.*
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/okfn-brasil/cuidando2/issues/67#issuecomment-133387723
> .

## 

## 

## Twitter: @_AleSou || GitHub: alexandre || Reddit: ubbersith

[...]o sentido disso tudo é que não há sentido em tentar enlouquecer
para impedir-se de ficar louco...guarde sua sanidade para mais
tarde[...] - Douglas Adams
